#!/bin/sh
#
#

set -e

usage="%0 (start|stop|restart|status)"

if [ $# -ne 1 ]; then
   echo $usage
   exit 1
fi


HBASE_SCRIPT_HOME=/usr/lib/hbase
if [ -e /lib/lsb/init-functions ]; then
   . /lib/lsb/init-functions
   SHOW_MSG=log_daemon_msg
   SHOW_RESULT=log_end_msg
else
   SHOW_MSG=echo
   SHOW_RESULT=show_result
fi

show_result() {
   if [ $1 -eq '0' ]; then
      echo '[OK]'
   fi
}

create_pid_dir() {
   mkdir -p /var/run/hadoop/hbase
   chown zookeeper:hadoop /var/run/hadoop/hbase
   chmod 0755 /var/run/hadoop/hbase
}

start_hbase() {
   if [ ! -d "$HBASE_SCRIPT_HOME" ] ; then
      echo "... directory $ZK_SCRIPT_HOME does not exist!" >&2
      return 1
   fi
   su hbase -c "$HBASE_SCRIPT_HOME/bin/hbase-daemon.sh start master"
}

stop_hbase() {
   if [ ! -d "$HBASE_SCRIPT_HOME" ] ; then
      echo "... directory $HBASE_SCRIPT_HOME does not exist!" >&2
      return 1
   fi
   su hbase -c "$HBASE_SCRIPT_HOME/bin/hbase-daemon.sh stop master"
}


case $1 in
   start)
      create_pid_dir
      $SHOW_MSG "Starting hbase master daemons"
      start_hbase
      $SHOW_RESULT 0
      ;;
   stop)
      $SHOW_MSG "Stopping hbase master daemons"
      stop_hbase
      $SHOW_RESULT 0
      ;;
   restart)
      $0 stop
      $0 start
      ;;
   status)
      jps
      ;;
   *)
      echo $usage
      ;;
esac
