#!/bin/sh
#
#

set -e

usage="/etc/init.d/hadoop (start|stop|restart|status)"

if [ $# -ne 1 ]; then
   echo $usage
   exit 1
fi


HADOOP_SCRIPT_HOME=/usr/sbin
if [ -x /lib/lsb/init-functions ]
   . /lib/lsb/init-functions
   SHOW_MEG=log_daemon_msg
   SHOW_RESULT=log_end_msg
elif
   SHOW_MEG=echo
   SHOW_RESULT=show_result
fi

show_result() {
   if [ $1 -eq '0' ]; then
      echo '[OK]'
   fi
}

create_pid_dir() {
   mkdir -p /var/run/hadoop/hdfs /var/run/hadoop/yarn /var/run/hadoop/mapred
   chown hdfs:hadoop /var/run/hadoop/hdfs
   chown yarn:hadoop /var/run/hadoop/yarn
   chown mapred:hadoop /var/run/hadoop/mapred
   chmod 0755 /var/run/hadoop/hdfs /var/run/hadoop/yarn /var/run/hadoop/mapred
}

start_hadoop_master() {
   if [ ! -d "$HADOOP_SCRIPT_HOME" ] ; then
      echo "... directory $HADOOP_SCRIPT_HOME does not exist!" >&2
      return 1
   fi
   su yarn -c "$HADOOP_SCRIPT_HOME/yarn-daemon.sh start resourcemanager"
   su hdfs -c "$HADOOP_SCRIPT_HOME/hadoop-daemon.sh --script hdfs start namenode"
   su mapred -c "$HADOOP_SCRIPT_HOME/mr-jobhistory-daemon.sh start historyserver"
}

start_hadoop_slave() {
   if [ ! -d "$HADOOP_SCRIPT_HOME" ] ; then
      echo "... directory $HADOOP_SCRIPT_HOME does not exist!" >&2
      return 1
   fi
   su yarn -c "$HADOOP_SCRIPT_HOME/yarn-daemon.sh start nodemanager"
   $HADOOP_SCRIPT_HOME/hadoop-daemon.sh --script hdfs start datanode
}

stop_hadoop_master() {
   if [ ! -d "$HADOOP_SCRIPT_HOME" ] ; then
      echo "... directory $HADOOP_SCRIPT_HOME does not exist!" >&2
      return 1
   fi
   su yarn -c "$HADOOP_SCRIPT_HOME/yarn-daemon.sh stop resourcemanager"
   su hdfs -c "$HADOOP_SCRIPT_HOME/hadoop-daemon.sh --script hdfs stop namenode"
   su mapred -c "$HADOOP_SCRIPT_HOME/mr-jobhistory-daemon.sh stop historyserver"
}

stop_hadoop_slave() {
   if [ ! -d "$HADOOP_SCRIPT_HOME" ] ; then
      echo "... directory $HADOOP_SCRIPT_HOME does not exist!" >&2
      return 1
   fi
   su yarn -c "$HADOOP_SCRIPT_HOME/yarn-daemon.sh stop nodemanager"
   $HADOOP_SCRIPT_HOME/hadoop-daemon.sh --script hdfs stop datanode
}


case $1 in
   start)
      create_pid_dir
      $SHOW_MSG "Starting hadoop master daemons"
      start_hadoop_master
      $SHOW_RESULT 0
      $SHOW_MSG "Starting hadoop slave daemons"
      start_hadoop_slave
      $SHOW_RESULT 0
      ;;
   stop)
      $SHOW_MSG "Stopping hadoop master daemons"
      stop_hadoop_master
      $SHOW_RESULT 0
      $SHOW_MSG "Stopping hadoop slave daemons"
      stop_hadoop_slave
      $SHOW_RESULT 0
      ;;
   restart)
      $0 stop
      $0 start
      ;;
   status)
      jps
      ;;
   *)
      echo $usage
      ;;
esac
